export { default as HomeHero } from './v3/HomeHeroV3';
export { default as NeedNavigator } from './v3/NeedNavigatorV3';
export { default as KediEcosystem } from './v3/KediEcosystemV3';
export { default as HomeGallery } from './v3/HomeGallery';
export { default as SolutionFlow } from './v3/SolutionFlowV3';
export { default as ServiceCapabilities } from './v3/ServiceCapabilitiesV3';
export { default as HomeProjects } from './v3/HomeProjectsV3';
export { default as HomeInsights } from './v3/HomeInsightsV3';
export { default as FinalCta } from './v3/FinalCtaV3';
