import { createProductMascot } from "../mascots";
import type { ProductLandingConfig } from "../types";

const base = "https://kikilogin.com/images/marketing";
const kediMascot = createProductMascot("kedi-profiles", "Kedi Profiles mascot 3D");

export const kediProfilesConfig: ProductLandingConfig = {
  slug: "kedi-profiles",
  productName: "Kedi Profiles",
  sourceLabel: "KikiLogin crawl",
  routeClass: "kedi-profiles-route",
  motionMascotSrc: kediMascot.src,
  hero: {
    eyebrow: "THE KEDI GROUP · KEDI PROFILES",
    titleLines: ["Tách biệt tài khoản,", "phân quyền đội ngũ,", "mở rộng bằng Kedi Profiles"],
    emphasisLine: 2,
    lead: "Kedi Profiles tổ chức multi-account browser theo profile độc lập: fingerprint riêng, dữ liệu cloud, quyền truy cập theo vai trò và khả năng mở rộng từ vài chục tới quy mô lớn mà không trộn lẫn phiên làm việc.",
    primaryCta: { label: "Xem 6 capability", href: "#bo-san-pham" },
    secondaryCta: { label: "Xem giao diện", href: "#giao-dien" },
    statusNote: "fingerprint · team · cloud · mobile profiles",
    mainImage: { src: `${base}/hero-screen-a.png`, alt: "Giao diện profile browser tham chiếu từ crawl KikiLogin", caption: "profile workspace · account isolation" },
    secondaryImage: { src: `${base}/kikilogin-fingerprint-baove-transparent-1000x780.png`, alt: "Minh họa fingerprint browser từ crawl KikiLogin", caption: "fingerprint độc lập cho từng profile" },
    floatingBadges: ["Role-based access", "Cloud sync · Mobile profiles"],
    mascot: kediMascot,
    stats: [
      { value: 6, label: "nhóm capability từ fingerprint tới agent" },
      { value: 4, label: "bước vận hành: tạo · phân quyền · đồng bộ · mở rộng" },
      { value: 3, label: "lớp thiết bị: desktop · Android · iOS" },
      { value: 1, label: "workspace để quản lý profile và nhân sự" },
    ],
  },
  marquee: ["Browser Fingerprint", "Profile Isolation", "Proxy", "Team Roles", "Cloud Sync", "Android Profile", "iOS Profile", "Account Status", "Automation API", "AI Agent", "Access Revocation", "Scale"],
  pain: {
    eyebrow: "01 · Chỗ tắc",
    titleLines: ["Nhiều tài khoản không khó,", "khó là giữ chúng thật sự tách biệt"],
    lead: "Khi profile, proxy, quyền truy cập và dữ liệu trình duyệt nằm ở nhiều chỗ, rủi ro không chỉ là thao tác chậm mà còn là tài khoản bị liên đới hoặc tài sản doanh nghiệp không còn rõ ai đang nắm giữ.",
    mascot: kediMascot,
    items: [
      { kicker: "Liên đới", title: "Nhiều tài khoản dùng chung dấu vân tay và phiên trình duyệt", description: "Đăng nhập nhiều nền tảng trong các session không được tách rõ khiến team khó kiểm soát cookie, fingerprint, proxy và lịch sử hoạt động của từng account." },
      { kicker: "Quyền truy cập", title: "Profile được chia bằng mật khẩu thay vì quyền theo vai trò", description: "Khi nhân sự thay đổi, việc thu hồi tài sản chậm và khó biết ai đang được phép mở profile nào." },
      { kicker: "Dữ liệu", title: "Session nằm trên từng máy cá nhân, đổi thiết bị là đứt luồng", description: "Cookie, cấu hình và trạng thái profile không đồng bộ khiến đội ngũ phải dựng lại môi trường hoặc chuyển dữ liệu thủ công." },
      { kicker: "Scale", title: "Càng nhiều profile càng tăng số thao tác vận hành", description: "Nếu mỗi profile là một quy trình riêng, tăng số tài khoản đồng nghĩa tăng cửa sổ, tăng lỗi cấu hình và tăng chi phí kiểm soát." },
    ],
  },
  modules: {
    eyebrow: "02 · Capability",
    title: "Sáu lớp để vận hành multi-account có cấu trúc",
    items: [
      { name: "Fingerprint Isolation", short: "Mỗi profile mang một dấu vân tay trình duyệt riêng thay vì chia sẻ cùng môi trường.", description: "Tách fingerprint, cookie và thông tin môi trường theo từng profile để mỗi account được quản lý như một workspace độc lập.", bullets: ["Fingerprint riêng cho từng profile", "Tách cookie và session", "Theo dõi trạng thái tài khoản theo profile"], image: { src: `${base}/kikilogin-fingerprint-baove-transparent-1000x780.png`, alt: "Fingerprint isolation reference" }, tag: "account isolation" },
      { name: "Profile Manager", short: "Tạo và quản lý số lượng lớn profile trong cùng một tài khoản vận hành.", description: "Profile manager gom việc tạo, nhóm, tìm kiếm và mở profile vào một nơi để đội ngũ không phải tự quản lý hàng loạt browser session rời.", bullets: ["Tạo profile theo bộ cấu hình", "Nhóm profile theo dự án hoặc khách hàng", "Mở rộng số profile mà không đổi quy trình"], image: { src: `${base}/feature-a.png`, alt: "Profile manager reference" }, tag: "profile scale" },
      { name: "Team Permissions", short: "Giao đúng profile cho đúng người, thu hồi quyền ngay khi cần.", description: "Tách quyền theo vai trò và theo profile giúp doanh nghiệp kiểm soát tài sản số mà không cần chia sẻ mật khẩu gốc.", bullets: ["Phân quyền theo thành viên", "Giới hạn profile được phép truy cập", "Thu hồi quyền khi nhân sự thay đổi"], image: { src: `${base}/kikilogin-quan-ly-doanh-nghiep-transparent.png`, alt: "Team permission reference" }, tag: "team control" },
      { name: "Cloud Sync", short: "Đồng bộ dữ liệu profile để đổi máy nhưng không đổi môi trường làm việc.", description: "Cloud sync giữ cấu hình và dữ liệu cần thiết của profile nhất quán giữa các thiết bị đã được cấp quyền.", bullets: ["Đồng bộ cấu hình profile", "Giảm thao tác chuyển dữ liệu thủ công", "Một tài khoản quản trị cho nhiều thiết bị"], image: { src: `${base}/feature-c.png`, alt: "Cloud sync reference" }, tag: "cloud workspace" },
      { name: "Mobile Profiles", short: "Mở rộng môi trường giả lập sang Android và iOS bên cạnh desktop.", description: "Capability mobile profile hỗ trợ các workflow cần thiết bị di động, thay vì ép mọi account phải chạy trong một fingerprint desktop duy nhất.", bullets: ["Profile Android", "Profile iOS", "Tách cấu hình mobile khỏi desktop"], image: { src: `${base}/feature-d.png`, alt: "Mobile profile reference" }, tag: "mobile device" },
      { name: "AI Operations", short: "Dùng ngôn ngữ tự nhiên để điều phối profile, proxy và tác vụ lặp.", description: "Lớp agent được định vị như trợ lý vận hành: nhận mục tiêu, chọn profile phù hợp và điều phối các bước lặp thay vì buộc người dùng dựng script cho mọi tình huống.", bullets: ["Điều phối profile và proxy", "Hỗ trợ tác vụ social / seeding", "Có thể kết hợp API automation cho workflow riêng"], image: { src: `${base}/feature-e.png`, alt: "AI operation reference" }, tag: "agent layer" },
    ],
  },
  workflow: {
    eyebrow: "03 · Vận hành",
    titleLines: ["Từ profile mới tới", "một workspace có kiểm soát"],
    lead: "Flow được tổ chức để dữ liệu môi trường, quyền nhân sự và trạng thái tài khoản đi cùng profile ngay từ đầu, thay vì xử lý sau khi account đã được chia cho nhiều người.",
    items: [
      { title: "Tạo profile và sinh fingerprint riêng", owner: "Kedi Profiles" },
      { title: "Gắn proxy, cookie và cấu hình môi trường", owner: "Kedi Profiles" },
      { title: "Phân profile cho đúng thành viên và vai trò", owner: "Kedi Profiles" },
      { title: "Đồng bộ dữ liệu profile qua workspace", owner: "Kedi Profiles" },
      { title: "Theo dõi trạng thái và mở rộng số lượng profile", owner: "Kedi Profiles" },
      { title: "Đội vận hành xem xét rủi ro theo chính sách từng nền tảng", keepHuman: true },
      { title: "Người phụ trách quyết định hành động kinh doanh trên account", keepHuman: true },
    ],
    humanSummary: "Kedi Profiles chuẩn hóa môi trường và quyền truy cập; quyết định về nội dung, chính sách nền tảng và rủi ro vận hành vẫn cần người chịu trách nhiệm.",
  },
  ecosystem: {
    eyebrow: "04 · Bản đồ hệ",
    titleLines: ["Profile là hạt nhân,", "fingerprint và quyền quay quanh nó"],
    lead: "Một profile chỉ thực sự có giá trị khi fingerprint, proxy, cloud sync, thành viên và automation cùng tham chiếu về đúng một định danh thay vì tồn tại như các cấu hình rời.",
    centerTitle: "Profile Core",
    centerSubtitle: "Identity · Access · Session",
    nodes: [
      { title: "Fingerprint", description: "Dấu vân tay độc lập" },
      { title: "Proxy", description: "Môi trường mạng theo profile" },
      { title: "Team", description: "Vai trò và quyền truy cập" },
      { title: "Cloud", description: "Đồng bộ dữ liệu" },
      { title: "Mobile", description: "Android & iOS profile" },
      { title: "Agent", description: "Automation layer" },
    ],
  },
  capability: {
    eyebrow: "05 · Capability map",
    titleLines: ["Đủ chi tiết để đội vận hành", "biết dữ liệu nào đang được tách"],
    lead: "Bảng dưới gom các capability nổi bật trong crawl thành những lớp dễ kiểm tra khi thiết kế hệ multi-account cho doanh nghiệp.",
    chips: ["Fingerprint", "Proxy", "Cloud", "Team Roles", "Mobile"],
    rows: [
      { label: "Profile isolation", value: "Fingerprint riêng · cookie riêng", why: "Giảm việc nhiều tài khoản dùng chung một môi trường trình duyệt." },
      { label: "Quản lý quy mô", value: "Từ nhóm nhỏ tới hàng nghìn profile", why: "Giữ cùng một cách quản trị khi số lượng account tăng." },
      { label: "Nhân sự", value: "Role-based access · revoke", why: "Không cần đưa mật khẩu hoặc toàn bộ tài sản cho từng thành viên." },
      { label: "Đồng bộ", value: "Cloud workspace", why: "Giữ profile nhất quán khi người dùng đổi máy hoặc làm việc theo team." },
      { label: "Thiết bị", value: "Desktop · Android · iOS", why: "Phù hợp nhiều workflow yêu cầu lớp thiết bị khác nhau." },
      { label: "Automation", value: "API + agent layer", why: "Cho phép điều phối tác vụ lặp mà vẫn giữ profile là đơn vị kiểm soát." },
    ],
    caption: "Capability map Kedi Profiles được chuẩn hóa từ nội dung crawl KikiLogin; số liệu marketing và bảng giá nguồn không được chuyển thành claim Kedi.",
  },
  gallery: {
    eyebrow: "06 · Giao diện tham chiếu",
    quote: "Profile, fingerprint, quyền nhân sự và khả năng mở rộng cần xuất hiện như một hệ thống duy nhất — không phải các màn hình quản trị không liên quan.",
    sourceNote: "Ảnh lấy từ output crawl KikiLogin để dựng prototype UI. Logo, testimonial và claim thương hiệu nguồn không được chuyển thành claim Kedi Profiles.",
    items: [
      { src: `${base}/hero-screen-a.png`, alt: "KikiLogin hero screen A", title: "Profile Workspace", description: "Không gian quản lý profile tập trung" },
      { src: `${base}/hero-screen-b.png`, alt: "KikiLogin hero screen B", title: "Browser Profiles", description: "Tách session theo từng profile" },
      { src: `${base}/kikilogin-fingerprint-baove-transparent-1000x780.png`, alt: "Fingerprint protection reference", title: "Fingerprint", description: "Môi trường độc lập cho tài khoản" },
      { src: `${base}/kikilogin-quan-ly-doanh-nghiep-transparent.png`, alt: "Team management reference", title: "Team Control", description: "Quyền truy cập theo nhân sự" },
      { src: `${base}/kikilogin-mo-rong-quy-mo-transparent-1200x860.png`, alt: "Scale reference", title: "Scale", description: "Mở rộng số lượng profile" },
      { src: `${base}/feature-e.png`, alt: "Automation feature reference", title: "Automation", description: "Agent và workflow vận hành" },
    ],
  },
  roadmap: {
    eyebrow: "07 · Quy trình",
    titleLines: ["Bốn bước đủ để", "đưa profile vào vận hành"],
    lead: "Quy trình được giữ đơn giản như cấu trúc nguồn: tạo profile, giao quyền, đồng bộ và mở rộng — mọi capability khác gắn quanh bốn điểm này.",
    steps: [
      { title: "Tạo profile", description: "Sinh fingerprint và môi trường riêng cho từng account.", meta: "Khởi tạo" },
      { title: "Phân quyền", description: "Giao profile cho đúng người và đúng vai trò.", meta: "Team" },
      { title: "Đồng bộ", description: "Giữ dữ liệu profile nhất quán giữa các thiết bị được phép.", meta: "Cloud" },
      { title: "Mở rộng", description: "Tăng số profile mà không đổi mô hình vận hành.", meta: "Scale" },
    ],
  },
  comparison: {
    eyebrow: "08 · Trước và sau",
    titleLines: ["Không phải mở nhiều browser hơn,", "mà là quản trị đúng đơn vị profile"],
    lead: "Sự khác biệt lớn nhất nằm ở cách tổ chức tài sản số: từ browser session phụ thuộc từng máy sang profile có định danh, fingerprint và quyền rõ ràng.",
    columns: [
      { label: "Browser session rời", title: "Mỗi máy giữ một phần tài sản", bullets: ["Cookie và session khó bàn giao", "Mật khẩu dễ bị chia sẻ", "Không rõ ai đang giữ profile nào", "Tăng account kéo theo tăng thao tác"], summary: "Phù hợp khi số account rất ít và chỉ một người trực tiếp quản lý." },
      { label: "Kedi Profiles", title: "Profile trở thành đơn vị quản trị", bullets: ["Fingerprint và session đi cùng profile", "Quyền theo vai trò thay vì chia password", "Cloud sync hỗ trợ team", "Automation bám vào đúng profile"], summary: "Dễ kiểm soát hơn khi số account, thiết bị và nhân sự cùng tăng.", accent: true },
    ],
  },
  faq: {
    eyebrow: "09 · Câu hỏi hay gặp",
    titleLines: ["Những câu cần trả lời", "trước khi scale multi-account"],
    lead: "Các câu hỏi tập trung vào khái niệm antidetect, fingerprint, dữ liệu cloud, mobile profile và ranh giới của automation.",
    mascot: kediMascot,
    items: [
      { question: "Antidetect browser khác gì mở nhiều cửa sổ trình duyệt?", answer: "Điểm chính là mỗi profile có fingerprint, cookie và cấu hình môi trường riêng thay vì chỉ mở nhiều tab hoặc nhiều cửa sổ trong cùng một browser identity." },
      { question: "Người mới có phải tự cấu hình fingerprint thủ công không?", answer: "Không nhất thiết. Flow Kedi Profiles được thiết kế để sinh cấu hình profile theo template, sau đó đội vận hành chỉ điều chỉnh các tham số cần thiết cho từng use case." },
      { question: "Dữ liệu profile có thể dùng trên nhiều máy không?", answer: "Có thể tổ chức theo cloud workspace và quyền thành viên. Mục tiêu là giữ cấu hình profile nhất quán mà không phải gửi file cookie hoặc chia sẻ mật khẩu qua kênh riêng." },
      { question: "Có hỗ trợ môi trường mobile không?", answer: "Capability map tham chiếu từ crawl có lớp profile Android và iOS bên cạnh desktop, phù hợp các workflow cần thiết bị di động." },
      { question: "AI agent có thay luôn đội vận hành không?", answer: "Không. Agent phù hợp phần lặp và điều phối; chính sách từng nền tảng, nội dung hoạt động và quyết định rủi ro vẫn phải có người chịu trách nhiệm." },
    ],
    closingTitle: "Cần map profile theo team hiện tại?",
    closingText: "Bắt đầu từ số account, số nhân sự, nền tảng đang vận hành và cách chia quyền hiện tại; Kedi Profiles sẽ được cấu hình quanh chính luồng đó.",
  },
  cta: {
    eyebrow: "Bước tiếp theo",
    titleLines: ["Biến hàng trăm browser session", "thành một profile workspace"],
    lead: "Bắt đầu bằng cách liệt kê profile đang có, ai đang giữ chúng, proxy nào đang dùng và dữ liệu nào cần bàn giao giữa các thiết bị. Đó là đủ để thiết kế cấu trúc Kedi Profiles.",
    mascot: kediMascot,
    sideTitle: "One profile workspace",
    sideText: "Fingerprint, session, proxy, team và automation cùng tham chiếu về một profile — dễ quản trị hơn khi doanh nghiệp mở rộng.",
  },
  sectionOrder: ["marquee", "pain", "modules", "workflow", "ecosystem", "capability", "gallery", "roadmap", "comparison", "faq", "cta"],
};
