import { createProductMascot } from "../mascots";
import type { ProductLandingConfig } from "../types";

const assets = "https://assets.capcutpilot.com/capcutpilot/landing/features";
const kediMascot = createProductMascot("kedi-video", "Kedi Video mascot 3D");

export const kediVideoConfig: ProductLandingConfig = {
  slug: "kedi-video",
  productName: "Kedi Video",
  sourceLabel: "CapCutPilot crawl",
  routeClass: "kedi-video-route",
  motionMascotSrc: kediMascot.src,
  hero: {
    eyebrow: "THE KEDI GROUP · KEDI VIDEO",
    titleLines: ["Edit một lần,", "áp cho cả batch,", "render bằng Kedi Video"],
    emphasisLine: 2,
    lead: "Kedi Video biến các thao tác lặp trong project CapCut thành workflow batch: sync footage, subtitle, effect, audio, color, keyframe, mask, AI generate và render queue mà không phải mở từng project để chỉnh lại cùng một việc.",
    primaryCta: { label: "Xem workflow", href: "#bo-san-pham" },
    secondaryCta: { label: "Xem ảnh feature", href: "#giao-dien" },
    statusNote: "batch editing · local processing · render queue",
    mainImage: { src: "https://capcutpilot.com/landing/hero/hero_1.jpeg", alt: "CapCutPilot hero preview dùng làm visual reference", caption: "batch edit · project automation" },
    secondaryImage: { src: "https://cdn.capcutpilot.com/landing/create-project/create-project.jpeg", alt: "Bulk create project reference", caption: "folder → nhiều project CapCut" },
    floatingBadges: ["Local processing", "Batch project · Render queue"],
    mascot: kediMascot,
    stats: [
      { value: 8, label: "nhóm automation từ sync tới AI generate" },
      { value: 3, label: "bước chính: chọn · cấu hình · chạy" },
      { value: 11, label: "nhóm tab chỉnh sửa được crawl" },
      { value: 100, label: "project trong capability bulk create tham chiếu" },
    ],
  },
  marquee: ["Smart Sync", "Subtitle", "Effects", "Transitions", "Animation", "Audio", "Color", "Keyframes", "Masks", "AI Generate", "Bulk Create", "Render Queue"],
  pain: {
    eyebrow: "01 · Chỗ tắc",
    titleLines: ["Không phải edit khó,", "mà là phải edit lại cùng một thứ 50 lần"],
    lead: "Các task lặp như subtitle style, hiệu ứng, LUT, âm thanh, keyframe và export không tạo thêm giá trị sáng tạo khi editor phải thao tác lại từng project.",
    mascot: kediMascot,
    items: [
      { kicker: "Effects", title: "Apply cùng hiệu ứng và transition cho từng project", description: "Một batch video có cùng format nhưng editor vẫn phải mở từng project, tìm đúng clip rồi áp lại effect, filter và transition." },
      { kicker: "Subtitle", title: "Style caption giống nhau nhưng phải chỉnh lại thủ công", description: "Font, position, animation và format subtitle lặp qua nhiều video khiến một thay đổi nhỏ phải làm lại trên toàn bộ batch." },
      { kicker: "Audio & Keyframe", title: "Âm thanh, SFX và keyframe bị dựng lại từ đầu", description: "Các pattern đã dùng tốt không có nơi lưu thành template để tái sử dụng cho project tiếp theo." },
      { kicker: "Render", title: "Export hàng chục project thành hàng chục lần chờ", description: "Không có queue tập trung khiến editor phải canh từng project, bấm export rồi quay lại mở project khác." },
    ],
  },
  modules: {
    eyebrow: "02 · Automation stack",
    title: "Sáu lớp edit dùng lại trên cả batch",
    items: [
      { name: "Smart Sync", short: "Căn footage với audio hoặc subtitle theo logic có thể lặp lại.", description: "Đồng bộ thông minh giúp xử lý những dự án có cấu trúc tương tự mà không phải kéo từng clip để khớp bằng mắt.", bullets: ["Căn clip theo audio / subtitle", "Áp logic sync cho nhiều project", "Giảm bước căn thủ công trước khi styling"], image: { src: `${assets}/sync/02.jpeg`, alt: "Smart sync feature reference" }, tag: "sync" },
      { name: "Subtitle Automation", short: "Đưa style caption thành preset thay vì chỉnh từng timeline.", description: "Chuẩn hóa style subtitle, vị trí, animation và các thuộc tính dùng lặp trên series video hoặc nhiều project cùng format.", bullets: ["Preset style caption", "Áp hàng loạt cho nhiều project", "Giữ visual consistency ở quy mô lớn"], image: { src: `${assets}/caption/01.jpeg`, alt: "Subtitle automation reference" }, tag: "caption" },
      { name: "Visual Style", short: "Effects, transitions, animation và filter đi cùng một rule set.", description: "Một cấu hình visual có thể áp cho toàn batch thay vì lặp thao tác thêm effect hoặc transition trên từng clip.", bullets: ["Effect và filter batch", "Transition / animation rule", "Giữ cùng visual language cho series"], image: { src: `${assets}/visual/01.jpeg`, alt: "Visual automation reference" }, tag: "visual" },
      { name: "Audio + Adjustment", short: "Âm thanh, SFX, color và adjustment được chuẩn hóa thành preset.", description: "Tách các quyết định âm thanh và màu khỏi thao tác lặp để editor chỉ cần cấu hình một lần cho cả batch.", bullets: ["Lớp audio và SFX", "Color / LUT / adjustment", "Có thể kết hợp voice effect theo workflow"], image: { src: `${assets}/sound/01.jpeg`, alt: "Audio automation reference" }, tag: "audio" },
      { name: "Keyframe Templates", short: "Lưu motion pattern để tái sử dụng thay vì dựng keyframe từ đầu.", description: "Các chuyển động lặp có thể biến thành template để áp lên clip hoặc layer tương ứng trong những project sau.", bullets: ["Preset keyframe", "Tái dùng motion pattern", "Giảm thao tác dựng lại animation"], image: { src: `${assets}/keyframe/01.jpeg`, alt: "Keyframe template reference" }, tag: "motion" },
      { name: "Workflow + Render", short: "Gom nhiều bước edit vào workflow và đẩy kết quả vào hàng đợi render.", description: "Editor cấu hình thứ tự thao tác, chạy batch và để render queue xử lý output thay vì bấm export từng project.", bullets: ["Workflow nhiều bước", "Render queue", "Kết hợp bulk create và AI Generate khi cần"], image: { src: `${assets}/workflow/01.jpeg`, alt: "Workflow automation reference" }, tag: "batch" },
    ],
  },
  workflow: {
    eyebrow: "03 · Đổi cách edit",
    titleLines: ["Editor chọn logic một lần,", "máy lặp phần còn lại"],
    lead: "Automation không thay phần quyết định sáng tạo. Nó lấy những thao tác đã được editor chốt — preset, rule, template, queue — rồi áp chúng nhất quán cho cả batch.",
    items: [
      { title: "Chọn folder hoặc nhóm project cần xử lý", owner: "Kedi Video" },
      { title: "Chọn preset sync, subtitle và visual style", owner: "Kedi Video" },
      { title: "Gắn audio, adjustment và keyframe template", owner: "Kedi Video" },
      { title: "Áp mask, video setting hoặc AI generation khi cần", owner: "Kedi Video" },
      { title: "Đưa project đã xử lý vào render queue", owner: "Kedi Video" },
      { title: "Editor review những project có ngoại lệ", keepHuman: true },
      { title: "Editor duyệt creative cuối và publish", keepHuman: true },
    ],
    humanSummary: "Máy lặp rule; editor giữ creative direction, xử lý ngoại lệ và duyệt output cuối. Đây là ranh giới giúp automation tăng tốc mà không biến video thành một batch vô hồn.",
  },
  ecosystem: {
    eyebrow: "04 · Bản đồ hệ",
    titleLines: ["Mọi automation quay quanh", "cùng một CapCut project flow"],
    lead: "Sync, caption, visual, audio, keyframe và render không nên là sáu tool rời; chúng là các stage của một project pipeline.",
    centerTitle: "Video Flow",
    centerSubtitle: "Project → Edit → Render",
    nodes: [
      { title: "Sync", description: "Footage alignment" },
      { title: "Caption", description: "Subtitle styling" },
      { title: "Visual", description: "Effect & transition" },
      { title: "Audio", description: "Sound & adjustment" },
      { title: "Keyframe", description: "Reusable motion" },
      { title: "Render", description: "Queue & output" },
    ],
  },
  capability: {
    eyebrow: "05 · Capability map",
    titleLines: ["Từ project file tới", "một dây chuyền edit cục bộ"],
    lead: "Các capability dưới đây được rút từ nội dung crawl CapCutPilot và nhóm lại theo cách một team video thực sự vận hành batch project.",
    chips: ["Local", "Batch", "Mask", "AI Generate", "Render Queue"],
    rows: [
      { label: "Xử lý dữ liệu", value: "100% local theo capability nguồn", why: "Project và media có thể được xử lý trên máy thay vì bắt buộc upload footage lên cloud." },
      { label: "Bulk project", value: "Folder → nhiều CapCut project", why: "Phù hợp với content factory có cấu trúc input giống nhau cho nhiều video." },
      { label: "Visual", value: "Effects · transitions · filters · animation", why: "Một rule set có thể áp đồng nhất lên nhiều project." },
      { label: "Audio", value: "Sound · SFX · voice effect", why: "Tách audio operation khỏi thao tác kéo thả thủ công từng timeline." },
      { label: "Advanced", value: "Mask · video setting · AI Generate", why: "Cho phép thêm các bước nâng cao vào cùng pipeline thay vì tách tool." },
      { label: "Output", value: "Auto render queue", why: "Giảm thời gian editor phải đứng canh từng project để export." },
    ],
    caption: "Capability map Kedi Video được chuẩn hóa từ crawl CapCutPilot; số liệu testimonial và claim marketing nguồn không được tái sử dụng như claim Kedi.",
  },
  gallery: {
    eyebrow: "06 · Feature gallery",
    quote: "Một trang video automation nên cho người xem thấy từng lớp thao tác thật — từ sync, caption và visual tới mask, AI Generate và render queue.",
    sourceNote: "Ảnh feature lấy từ output crawl CapCutPilot để kiểm tra cách bố trí và chiều sâu nội dung trong pilot Kedi Video.",
    items: [
      { src: `${assets}/sync/02.jpeg`, alt: "Sync reference", title: "Smart Sync", description: "Căn footage với audio / subtitle" },
      { src: `${assets}/caption/01.jpeg`, alt: "Caption reference", title: "Subtitle", description: "Tự động hóa style caption" },
      { src: `${assets}/visual/01.jpeg`, alt: "Visual feature reference", title: "Visual", description: "Effects, transitions và filters" },
      { src: `${assets}/sound/01.jpeg`, alt: "Audio feature reference", title: "Audio", description: "Sound layer và SFX" },
      { src: `${assets}/adjustment/01.jpeg`, alt: "Adjustment reference", title: "Color", description: "Adjustment và color preset" },
      { src: `${assets}/keyframe/01.jpeg`, alt: "Keyframe reference", title: "Keyframe", description: "Template motion dùng lại" },
      { src: `${assets}/media-video/01.jpeg`, alt: "Mask reference", title: "Mask & Video", description: "Video setting nâng cao" },
      { src: `${assets}/auto-render/01.jpeg`, alt: "Render queue reference", title: "Render Queue", description: "Tự động xử lý output" },
    ],
  },
  roadmap: {
    eyebrow: "07 · Ba bước chính",
    titleLines: ["Chọn project, cấu hình,", "rồi để batch tự chạy"],
    lead: "Nguồn crawl mô tả workflow rất gọn. Kedi Video giữ tinh thần đó nhưng thêm một bước review cuối để phù hợp vận hành team.",
    steps: [
      { title: "Chọn project", description: "Chọn folder, batch hoặc nhóm project cần xử lý.", meta: "Input" },
      { title: "Cấu hình chỉnh sửa", description: "Chọn preset, effect, caption, audio, keyframe và rule cần áp.", meta: "Rules" },
      { title: "Chạy & render", description: "Áp workflow và đưa project vào hàng đợi output.", meta: "Batch" },
      { title: "Review ngoại lệ", description: "Editor xem những video cần can thiệp trước khi publish.", meta: "Human review" },
    ],
  },
  comparison: {
    eyebrow: "08 · Manual vs batch",
    titleLines: ["Giữ quyết định sáng tạo,", "loại bỏ phần click lặp"],
    lead: "So sánh này tập trung vào cách làm việc thay vì lặp lại số liệu marketing của nguồn.",
    columns: [
      { label: "Edit thủ công", title: "Mỗi project là một vòng thao tác", bullets: ["Mở từng project", "Áp lại style và effect", "Dựng lại keyframe / audio", "Export từng video"], summary: "Ổn với vài video; bắt đầu tốn thời gian khi format giống nhau nhưng số lượng tăng." },
      { label: "Kedi Video", title: "Một rule set chạy trên cả batch", bullets: ["Chọn project theo nhóm", "Tái sử dụng preset và template", "Queue các bước edit", "Render output tập trung"], summary: "Editor tập trung vào creative và ngoại lệ thay vì lặp lại cùng thao tác.", accent: true },
    ],
  },
  faq: {
    eyebrow: "09 · Câu hỏi hay gặp",
    titleLines: ["Những câu editor sẽ hỏi", "trước khi giao project cho automation"],
    lead: "FAQ tập trung vào nơi xử lý dữ liệu, cloud, file project và ranh giới giữa automation với creative review.",
    mascot: kediMascot,
    items: [
      { question: "Video có phải upload lên cloud để xử lý không?", answer: "Capability tham chiếu từ crawl mô tả mô hình xử lý tại máy. Điều này phù hợp các team muốn giữ footage và project trong môi trường local." },
      { question: "Automation can thiệp trực tiếp vào tài khoản CapCut không?", answer: "Mô hình nguồn tập trung vào chỉnh file project và workflow cục bộ, không cần biến automation thành bot thao tác tài khoản cloud." },
      { question: "Có thể tái sử dụng style subtitle và keyframe không?", answer: "Có. Hai nhóm capability chính là subtitle automation và keyframe template, nhằm biến style đã chốt thành preset dùng lại cho nhiều project." },
      { question: "Có hỗ trợ mask, audio và voice effect không?", answer: "Capability map có các nhóm video/mask, audio processing, adjustment và voice effect để chúng có thể tham gia cùng workflow batch." },
      { question: "Có nên để automation publish luôn không?", answer: "Không nhất thiết. Kedi Video ưu tiên tự động hóa phần lặp và render; creative review, kiểm tra ngoại lệ và quyết định publish vẫn nên có người chịu trách nhiệm." },
    ],
    closingTitle: "Có batch project thực tế để thử?",
    closingText: "Chọn một series video có cấu trúc lặp rõ nhất; đó là nơi dễ đo hiệu quả của automation trước khi mở rộng sang toàn bộ pipeline.",
  },
  cta: {
    eyebrow: "Bước tiếp theo",
    titleLines: ["Lấy batch video đang edit tay", "làm workflow đầu tiên"],
    lead: "Không cần tự động hóa mọi thứ ngay. Chọn một batch có cùng subtitle style, effect, audio hoặc render setting — rồi biến đúng phần lặp đó thành workflow Kedi Video.",
    mascot: kediMascot,
    sideTitle: "Batch edit, human review",
    sideText: "Máy lặp preset và queue; editor giữ creative direction, ngoại lệ và quyết định publish.",
  },
  sectionOrder: ["marquee", "pain", "modules", "workflow", "ecosystem", "capability", "gallery", "roadmap", "comparison", "faq", "cta"],
};
