import { createProductMascot } from "../mascots";
import type { ProductLandingConfig } from "../types";

const base = "https://zecom.auto-agents.org/assets/img";
const kediMascot = createProductMascot("kedi-pod", "Kedi POD mascot 3D");

export const kediPodConfig: ProductLandingConfig = {
  slug: "kedi-pod",
  productName: "Kedi POD",
  sourceLabel: "ZECOM crawl",
  routeClass: "kedi-pod-route",
  motionMascotSrc: kediMascot.src,
  hero: {
    eyebrow: "THE KEDI GROUP · KEDI POD",
    titleLines: ["Từ keyword tới", "design, listing và file in", "trong một POD workstation"],
    emphasisLine: 2,
    lead: "Kedi POD gom nghiên cứu keyword, lọc cơ hội, cảnh báo bản quyền, AI design, mockup, listing SEO và xuất file in vào cùng một workflow cho seller Print-on-Demand.",
    primaryCta: { label: "Xem workflow POD", href: "#bo-san-pham" },
    secondaryCta: { label: "Xem design gallery", href: "#giao-dien" },
    statusNote: "research · design · listing · export",
    mainImage: { src: `${base}/app/workstation.webp`, alt: "POD workstation tham chiếu từ crawl ZECOM", caption: "POD workstation · market to listing" },
    secondaryImage: { src: `${base}/designs/design-01.webp`, alt: "AI design sample tham chiếu", caption: "design & mockup output" },
    floatingBadges: ["Etsy · Amazon", "300 DPI · CSV/ZIP"],
    mascot: kediMascot,
    stats: [
      { value: 6, label: "bước workflow từ keyword tới file xuất" },
      { value: 10, label: "nhóm capability được crawl" },
      { value: 2, label: "marketplace trọng tâm: Etsy · Amazon" },
      { value: 300, suffix: " DPI", label: "mức file in trong capability nguồn" },
    ],
  },
  marquee: ["Trend Hunter", "Market Research", "Competitor", "Trademark Risk", "AI Design", "Background Remove", "Mockup", "Listing SEO", "Helium 10", "Anti-detect", "Agent Chat", "Export"],
  pain: {
    eyebrow: "01 · Chỗ tắc",
    titleLines: ["Team POD không thiếu tool,", "team thiếu một flow chạy từ A tới Z"],
    lead: "Research, trademark, design, mockup và listing thường bị chia thành nhiều công cụ. Mỗi lần chuyển chỗ là một lần copy dữ liệu, mất ngữ cảnh và khó scale quy trình đã chạy tốt.",
    mascot: kediMascot,
    items: [
      { kicker: "Research", title: "Keyword và dữ liệu thị trường nằm ở nhiều nguồn", description: "Seller phải nối Google Trends, Etsy, Amazon, Pinterest hoặc dữ liệu Helium 10 bằng tay trước khi có shortlist sản phẩm." },
      { kicker: "Trademark", title: "Kiểm tra rủi ro bản quyền thường diễn ra quá muộn", description: "Nếu cảnh báo trademark chỉ xuất hiện sau khi design đã hoàn tất, toàn bộ thời gian research và creative có thể phải làm lại." },
      { kicker: "Design", title: "Design, tách nền và mockup là ba vòng thao tác riêng", description: "Một ý tưởng đi qua nhiều app rồi mới thành file in và mockup khiến batch sản phẩm khó giữ nhịp." },
      { kicker: "Listing", title: "Title, tag, mô tả và file export bị tách khỏi research gốc", description: "Khi listing không còn liên kết với keyword và dữ liệu đối thủ, seller phải tự ghép lại logic SEO ở cuối quy trình." },
    ],
  },
  modules: {
    eyebrow: "02 · POD workstation",
    title: "Sáu capability phủ trọn vòng đời một listing",
    items: [
      { name: "Trend & Market Research", short: "Quét xu hướng, sản phẩm và đối thủ trước khi đầu tư creative.", description: "Gom keyword, trend và market data thành một shortlist đủ rõ để seller biết ý tưởng nào đáng thử trước.", bullets: ["Google Trends / marketplace signals", "Phân tích top seller và mức cạnh tranh", "Có thể dùng dữ liệu Helium 10 làm đầu vào"], image: { src: `${base}/app/workstation.webp`, alt: "Market research workstation reference" }, tag: "research" },
      { name: "Trademark Risk", short: "Đưa cảnh báo bản quyền vào sớm trong workflow thay vì kiểm tra ở cuối.", description: "Lớp risk check tham chiếu các nguồn trademark để gắn cảnh báo trước khi seller tiếp tục design hoặc listing.", bullets: ["Cảnh báo rủi ro theo keyword", "Tham chiếu nguồn trademark", "Là tín hiệu hỗ trợ, không thay tư vấn pháp lý"], image: { src: `${base}/designs/design-02.webp`, alt: "Trademark stage visual reference" }, tag: "risk" },
      { name: "AI Design", short: "Từ research mẫu bán tốt tới brief và design mới có thể duyệt.", description: "Agent tạo brief và phương án design để seller duyệt thay vì bắt team bắt đầu từng file từ canvas trắng.", bullets: ["Design brief từ research", "Tạo nhiều phương án thử nghiệm", "Seller giữ bước duyệt creative"], image: { src: `${base}/designs/design-03.webp`, alt: "AI design reference" }, tag: "creative" },
      { name: "Mockup Pipeline", short: "Tách nền và ráp mockup hàng loạt trong cùng flow design.", description: "Sau khi chọn creative, workflow tiếp tục tách nền, chuẩn bị file in và ráp mockup thay vì chuyển qua công cụ khác.", bullets: ["Background removal", "Mockup batch", "File in theo chuẩn output"], image: { src: `${base}/designs/design-04.webp`, alt: "Mockup reference" }, tag: "mockup" },
      { name: "Listing SEO", short: "Biến keyword đã research thành title, tags và description cho marketplace.", description: "Listing giữ liên kết với dữ liệu đầu vào để SEO không bị trở thành một bước viết lại độc lập ở cuối pipeline.", bullets: ["Title và tag theo keyword", "Description tối ưu cho listing", "Export dữ liệu theo file có cấu trúc"], image: { src: `${base}/designs/design-05.webp`, alt: "Listing SEO reference" }, tag: "listing" },
      { name: "Agent Workflow", short: "Ra lệnh bằng ngôn ngữ tự nhiên để gọi đúng skill trong workstation.", description: "Agent layer nối các capability thành workflow có thể lặp: research, competitor analysis, design brief, listing optimization và batch design.", bullets: ["Natural-language command", "Skill-based execution", "Workflow nhiều bước có thể tái sử dụng"], image: { src: `${base}/designs/design-06.webp`, alt: "Agent workflow reference" }, tag: "agent" },
    ],
  },
  workflow: {
    eyebrow: "03 · POD từ A tới Z",
    titleLines: ["Bạn nhập keyword,", "agent chuẩn bị phần còn lại để duyệt"],
    lead: "Workflow giữ đúng tinh thần nguồn crawl: automation xử lý những bước có thể chuẩn hóa; seller vẫn quyết định keyword nào đáng theo và design nào đủ tốt để xuất bản.",
    items: [
      { title: "Nghiên cứu keyword từ marketplace và trend signals", owner: "Kedi POD" },
      { title: "Lọc cơ hội theo nhu cầu và cạnh tranh", owner: "Kedi POD" },
      { title: "Gắn cảnh báo trademark / copyright risk", owner: "Kedi POD" },
      { title: "Tạo design brief, phương án design và mockup", owner: "Kedi POD" },
      { title: "Sinh title, tags, description và bộ file export", owner: "Kedi POD" },
      { title: "Seller duyệt ý tưởng và design cuối", keepHuman: true },
      { title: "Seller quyết định publish, giá và chiến lược quảng cáo", keepHuman: true },
    ],
    humanSummary: "Research và production có thể được tự động hóa sâu; creative approval, bản quyền, giá bán và quyết định publish vẫn là phần con người cần chịu trách nhiệm.",
  },
  ecosystem: {
    eyebrow: "04 · Bản đồ hệ",
    titleLines: ["Keyword là điểm vào,", "listing là điểm ra"],
    lead: "Các module được tổ chức như một pipeline thay vì một menu tool: research tạo dữ liệu cho risk check, design và listing; output cuối quay lại thành tín hiệu cho vòng thử nghiệm tiếp theo.",
    centerTitle: "POD Flow",
    centerSubtitle: "Keyword → Design → Listing",
    nodes: [
      { title: "Trend", description: "Keyword & market signals" },
      { title: "Risk", description: "Trademark warning" },
      { title: "Design", description: "Creative generation" },
      { title: "Mockup", description: "Background & product mockup" },
      { title: "Listing", description: "SEO title / tags / description" },
      { title: "Export", description: "Print file · CSV/ZIP" },
    ],
  },
  gallery: {
    eyebrow: "05 · Design gallery",
    quote: "POD cần nhiều phương án creative để thử nghiệm. Gallery dùng chính các mẫu design crawl được để kiểm tra cách trang xử lý một lượng hình lớn mà vẫn giữ nhịp đọc.",
    sourceNote: "Ảnh workstation và design lấy từ crawl ZECOM. Đây là visual reference cho prototype Kedi POD, không phải portfolio hay claim sở hữu của Kedi.",
    items: [
      { src: `${base}/app/workstation.webp`, alt: "POD workstation reference", title: "Workstation", description: "Research, inventory và AI creative" },
      { src: `${base}/designs/design-01.webp`, alt: "POD design 1", title: "Design 01", description: "Creative sample từ crawl" },
      { src: `${base}/designs/design-02.webp`, alt: "POD design 2", title: "Design 02", description: "Creative sample từ crawl" },
      { src: `${base}/designs/design-03.webp`, alt: "POD design 3", title: "Design 03", description: "Creative sample từ crawl" },
      { src: `${base}/designs/design-04.webp`, alt: "POD design 4", title: "Design 04", description: "Creative sample từ crawl" },
      { src: `${base}/designs/design-05.webp`, alt: "POD design 5", title: "Design 05", description: "Creative sample từ crawl" },
      { src: `${base}/designs/design-06.webp`, alt: "POD design 6", title: "Design 06", description: "Creative sample từ crawl" },
      { src: `${base}/designs/design-07.webp`, alt: "POD design 7", title: "Design 07", description: "Creative sample từ crawl" },
    ],
  },
  faq: {
    eyebrow: "06 · Câu hỏi hay gặp",
    titleLines: ["Những câu seller sẽ hỏi", "trước khi giao workflow cho agent"],
    lead: "FAQ giữ lại các câu thực tế nhất trong nguồn crawl: marketplace, hệ điều hành, no-code, design, trademark và multi-account.",
    mascot: kediMascot,
    items: [
      { question: "Workflow POD tập trung vào marketplace nào?", answer: "Capability nguồn tập trung vào Etsy và Amazon Merch, đồng thời lấy thêm tín hiệu từ Google Trends, Pinterest và dữ liệu research khác." },
      { question: "Người không biết code có dùng workflow agent được không?", answer: "Có. Lớp agent được thiết kế để nhận mục tiêu bằng ngôn ngữ tự nhiên rồi gọi đúng skill trong workstation; người dùng chủ yếu nhập keyword và duyệt output." },
      { question: "AI design có tự publish luôn không?", answer: "Không nên mặc định như vậy. Kedi POD giữ seller ở bước duyệt creative và quyết định publish; automation tập trung research, production và chuẩn bị listing." },
      { question: "Cảnh báo trademark có thay tư vấn pháp lý không?", answer: "Không. Nó chỉ là tín hiệu rủi ro dựa trên nguồn tham chiếu để seller cân nhắc trước khi đăng sản phẩm." },
      { question: "Có thể vận hành nhiều tài khoản không?", answer: "Capability nguồn có lớp anti-detect browser và xử lý nhiều account. Khi triển khai Kedi POD, phần này cần được map theo marketplace và chính sách tài khoản thực tế." },
    ],
    closingTitle: "Có một niche POD muốn thử?",
    closingText: "Chỉ cần một keyword, một marketplace mục tiêu và tiêu chí duyệt design; đó là đủ để dựng workflow thử nghiệm đầu tiên.",
  },
  cta: {
    eyebrow: "Bước tiếp theo",
    titleLines: ["Đưa một niche POD", "chạy trọn workflow đầu tiên"],
    lead: "Bắt đầu nhỏ: một keyword, một batch research, vài phương án design và một listing mẫu. Nếu flow chạy đúng, mới nhân bản sang niche và store tiếp theo.",
    mascot: kediMascot,
    sideTitle: "Keyword to listing",
    sideText: "Research, risk, design, mockup và listing đi cùng một data flow; seller chỉ giữ những quyết định cần phán đoán.",
  },
  sectionOrder: ["marquee", "pain", "modules", "workflow", "ecosystem", "gallery", "faq", "cta"],
};
