export const storyData = [
  {
    id: 1,
    src: 'https://mona.media/template/assets/hq-images/customer-intro/solution_kimthanh.jpg',
    alt: 'Khách hàng Kim Thành',
    desc: 'Tất niên về anh em Mona thất lạc kính. Không sao, có Mắt Việt tài trợ rồi!',
    date: 'Ngày 10/01/2023',
  },
  {
    id: 2,
    src: 'https://mona.media/template/assets/hq-images/customer-intro/solution_kimthanh.jpg',
    alt: 'Khách hàng 2',
    desc: '"Ở công ty bị sếp đi, ra ngoài tụi em đi sếp nhé nhé"',
    date: 'Ngày 14/03/2023',
  },
  {
    id: 3,
    src: 'https://mona.media/template/assets/hq-images/customer-intro/solution_kimthanh.jpg',
    alt: 'Khách hàng 3',
    desc: 'Khách alo nhậu, Mona có mặt! Ngày họp fan bóng đá của Mona và khách.',
    date: 'Ngày 10/01/2023',
  },
  {
    id: 4,
    src: 'https://mona.media/template/assets/hq-images/customer-intro/solution_kimthanh.jpg',
    alt: 'Khách hàng 4',
    desc: 'Mona Media cứ lo tổ chức tiệc, rượu nhậu Kim Thành tài trợ khỏi lo!',
    date: 'Ngày 13/01/2023',
  },
  {
    id: 5,
    src: 'https://mona.media/template/assets/hq-images/customer-intro/solution_kimthanh.jpg',
    alt: 'Khách hàng 5',
    desc: 'Khách hàng 5 nói gì đó...',
    date: 'Ngày 15/02/2023',
  },
  {
    id: 6,
    src: 'https://mona.media/template/assets/hq-images/customer-intro/solution_kimthanh.jpg',
    alt: 'Khách hàng 6',
    desc: 'Khách hàng 6 nói gì đó...',
    date: 'Ngày 20/02/2023',
  },
  {
    id: 7,
    src: 'https://mona.media/template/assets/hq-images/customer-intro/solution_kimthanh.jpg',
    alt: 'Khách hàng 7',
    desc: 'Khách hàng 7 nói gì đó...',
    date: 'Ngày 25/02/2023',
  },
  {
    id: 8,
    src: 'https://mona.media/template/assets/hq-images/customer-intro/solution_kimthanh.jpg',
    alt: 'Khách hàng 8',
    desc: 'Khách hàng 8 nói gì đó...',
    date: 'Ngày 28/02/2023',
  },
  {
    id: 9,
    src: 'https://mona.media/template/assets/hq-images/customer-intro/solution_kimthanh.jpg',
    alt: 'Khách hàng 9',
    desc: 'Khách hàng 9 nói gì đó...',
    date: 'Ngày 05/03/2023',
  },
  {
    id: 10,
    src: 'https://mona.media/template/assets/hq-images/customer-intro/solution_kimthanh.jpg',
    alt: 'Khách hàng 10',
    desc: 'Khách hàng 10 nói gì đó...',
    date: 'Ngày 10/03/2023',
  },
  {
    id: 11,
    src: 'https://mona.media/template/assets/hq-images/customer-intro/solution_kimthanh.jpg',
    alt: 'Khách hàng 11',
    desc: 'Khách hàng 11 nói gì đó...',
    date: 'Ngày 15/03/2023',
  },
  {
    id: 12,
    src: 'https://mona.media/template/assets/hq-images/customer-intro/solution_kimthanh.jpg',
    alt: 'Khách hàng 12',
    desc: 'Khách hàng 12 nói gì đó...',
    date: 'Ngày 20/03/2023',
  },
];
